name: Hellow world workflow

on:
    push:
      branches: 
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v2
        - name: hello world
          run: bash echo "Hello world"
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye-world
        run: bash echo "Goodbye world"
